In [7]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("data.csv")
print(df.head())

               country  child_mort  exports  health  imports  income  \
0          Afghanistan        90.2     10.0    7.58     44.9    1610   
1              Albania        16.6     28.0    6.55     48.6    9930   
2              Algeria        27.3     38.4    4.17     31.4   12900   
3               Angola       119.0     62.3    2.85     42.9    5900   
4  Antigua and Barbuda        10.3     45.5    6.03     58.9   19100   

   inflation  life_expec  total_fer   gdpp  
0       9.44        56.2       5.82    553  
1       4.49        76.3       1.65   4090  
2      16.10        76.5       2.89   4460  
3      22.40        60.1       6.16   3530  
4       1.44        76.8       2.13  12200  


In [9]:
df = pd.read_csv("data.csv")
df = df.drop(columns=['country'])  # drop 'country' column completely

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [10]:
print("X shape:", X.shape)
print("X dtype:", X.dtype)
print("y shape:", y.shape)
print("y dtype:", y.dtype)

print("Example X row:", X[0])


X shape: (167, 8)
X dtype: float64
y shape: (167,)
y dtype: int64
Example X row: [  90.2    10.      7.58   44.9  1610.      9.44   56.2     5.82]


In [11]:
def euclidean_distance(a, b):
    print(type(a), type(b))
    print(a, b)
    return np.sqrt(np.sum((a - b)**2))


In [12]:
def train_test_split(X, y, test_size=0.2):
    n = len(X)
    indices = np.random.permutation(n)
    test_count = int(n * test_size)
    
    test_idx = indices[:test_count]
    train_idx = indices[test_count:]
    
    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]

X_train, X_test, y_train, y_test = train_test_split(X, y)


In [13]:
def knn_predict(X_train, y_train, x_test, k=3):
    # Compute distance from x_test to each training example
    distances = [euclidean_distance(x_test, x) for x in X_train]
    
    # Sort by distance and pick k nearest neighbors
    k_indices = np.argsort(distances)[:k]
    
    # Extract labels of these neighbors
    k_nearest_labels = y_train[k_indices]
    
    # Majority vote
    values, counts = np.unique(k_nearest_labels, return_counts=True)
    return values[np.argmax(counts)]


In [14]:
def knn_predict_batch(X_train, y_train, X_test, k=3):
    predictions = []
    for x in X_test:
        pred = knn_predict(X_train, y_train, x, k)
        predictions.append(pred)
    return np.array(predictions)

y_pred = knn_predict_batch(X_train, y_train, X_test, k=5)


<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.92e+01 2.69e+01 6.91e+00 4.66e+01 7.30e+03 2.65e+00 7.41e+01 2.27e+00] [  80.3    23.8     5.69   42.7  1660.      4.3    65.5     5.71]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.92e+01 2.69e+01 6.91e+00 4.66e+01 7.30e+03 2.65e+00 7.41e+01 2.27e+00] [1.06e+01 2.63e+01 8.35e+00 2.54e+01 1.71e+04 4.91e+00 7.64e+01 2.08e+00]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.92e+01 2.69e+01 6.91e+00 4.66e+01 7.30e+03 2.65e+00 7.41e+01 2.27e+00] [  97.4    50.7     4.41   61.2  3320.     18.9    68.2     4.98]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.92e+01 2.69e+01 6.91e+00 4.66e+01 7.30e+03 2.65e+00 7.41e+01 2.27e+00] [4.10e+00 4.94e+01 6.93e+00 4.62e+01 3.04e+04 3.16e+00 8.01e+01 1.23e+00]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.92e+01 2.69e+01 6.91e+00 4.66e+01 7.30e+03 2.65e+00 7.41e+01 2.27e+00] [  40.     23.5    14.2    81.   3340.      3.8    65.4     3.46]
<class 'numpy.ndarray'> <class 'numpy.ndarra

In [15]:
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)


Accuracy: 0.030303030303030304
